name: PVP-Plugin
version: 3
main: src.Kitpvp

commands:
  gamemaster:
    description: Changes into Gamemaster.
  ratchet:
    description: Plays a particle effect.
  kits:
    description: Opens the kits GUI.

